always_train_batchnorm: false
class_weights: null
cosine_schedule: true
dropout_prob: 0.5
from_scratch: false
label_smoothing: 0.0
learning_rate: 1.0e-05
lr_decay: 0.25
max_cosine_epochs: 100
max_learning_rate_reduction_factor: 0.01
n_blocks: 5
n_layers: 0
name: hf_hub:mwalmsley/zoobot-encoder-convnext_nano
num_classes: 10
prog_bar: true
seed: 42
visualize_images: false
warmup_epochs: 0
weight_decay: 0.1
zoobot_checkpoint_loc: null
